
export const reinfCodes = [
    { code: '17001', description: 'Alimentação' },
    { code: '17002', description: 'Energia elétrica' },
    { code: '17003', description: 'Serviços prestados com emprego de materiais' },
    { code: '17004', description: 'Construção Civil por empreitada' },
    { code: '17005', description: 'Serviços hospitalares' },
    { code: '17006', description: 'Transporte de cargas' },
    { code: '17007', description: 'Serviços de auxílio diagnóstico e terapia' },
    { code: '17008', description: 'Produtos farmacêuticos e de perfumaria' },
    { code: '17009', description: 'Mercadorias e bens em geral' },
    { code: '17010', description: 'Gasolina, inclusive de aviação' },
    { code: '17011', description: 'Álcool etílico hidratado' },
    { code: '17012', description: 'Biodiesel adquirido de produtor ou importador' },
    { code: '17013', description: 'Gasolina, exceto gasolina de aviação' },
    { code: '17014', description: 'Álcool etílico hidratado nacional para fins carburantes' },
    { code: '17015', description: 'Biodiesel adquirido de distribuidor' },
    { code: '17016', description: 'Biodiesel adquirido de produtor com selo social' },
    { code: '17017', description: 'Transporte internacional de cargas' },
    { code: '17018', description: 'Estaleiros navais brasileiros' },
    { code: '17019', description: 'Produtos de perfumaria, toucador ou higiene' },
    { code: '17020', description: 'Produtos ref. § 2º art. 2º Lei 10.485' },
    { code: '17021', description: 'Produtos ref. alíneas "b" e "c" § 3º art. 2º Lei 10.485' },
    { code: '17022', description: 'Outros produtos ou serviços com alíquota zero' },
    { code: '17023', description: 'Passagens aéreas, rodoviárias e transporte de passageiros' },
    { code: '17024', description: 'Transporte internacional de passageiros' },
    { code: '17025', description: 'Serviços prestados por associações profissionais' },
    { code: '17026', description: 'Serviços prestados por bancos e inst. financeiras' },
    { code: '17027', description: 'Seguro Saúde' },
    { code: '17028', description: 'Serviços de abastecimento de água' },
    { code: '17029', description: 'Telefone' },
    { code: '17030', description: 'Correio e telégrafos' },
    { code: '17031', description: 'Vigilância' },
    { code: '17032', description: 'Limpeza' },
    { code: '17033', description: 'Locação de mão de obra' },
    { code: '17034', description: 'Intermediação de negócios' },
    { code: '17035', description: 'Administração, locação ou cessão de bens' },
    { code: '17036', description: 'Factoring' },
    { code: '17037', description: 'Plano de saúde humano, veterinário ou odontológico' },
    { code: '17038', description: 'Pagamento a sociedade civil de prestação de serviços' },
    { code: '17039', description: 'Pagamento a Cooperativa de trabalho' },
    { code: '17040', description: 'Serviços prestados por associações de saúde' },
    { code: '17041', description: 'Serviços prestados por associações de transporte' },
    { code: '17042', description: 'Pagamentos efetuados às associações e cooperativas' },
    { code: '17043', description: 'Pagamento efetuado a sociedade simples' },
    { code: '17044', description: 'Pagamento referente a aluguel de bens' },
    { code: '17045', description: 'Serviços prestados por cooperativas de trabalho' },
    { code: '17046', description: 'Pagamento na aquisição de autopeças' },
    { code: '17047', description: 'Pagamento na aquisição de máquinas e veículos' },
    { code: '17048', description: 'Pagamento na aquisição de bens para revenda' },
    { code: '17049', description: 'Propaganda e Publicidade' },
    { code: '17050', description: 'Propaganda e Publicidade, exceto rádio e TV' },
    { code: '17051', description: 'Pagamentos a entidades imunes ou isentas' },
    { code: '17099', description: 'Demais serviços' },
  ];
